name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  APP_NAME: my-demo-app

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show env vars
        run: |
          echo "App: $APP_NAME"
          echo "Env: $BUILD_ENV"

      - name: Cache example
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: ${{ runner.os }}-cache-${{ github.sha }}

      - name: Build step
        run: echo "Build successful"
